// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PaperStoneScissors.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [MbUnit.Framework.TestFixtureAttribute()]
    [MbUnit.Framework.DescriptionAttribute("In order to play a game that finishes in a fixed maximum number of rounds\r\nAs a P" +
        "aper Stone Scissors enthusiast\r\nI want to be able to play a game that finishes w" +
        "hen a user wins the majority of a fixed number of rounds")]
    public partial class Best_OfStyleGamePlayFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BestOfGame.feature"
#line hidden
        
        [MbUnit.Framework.FixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Best-Of Style Game Play", "In order to play a game that finishes in a fixed maximum number of rounds\r\nAs a P" +
                    "aper Stone Scissors enthusiast\r\nI want to be able to play a game that finishes w" +
                    "hen a user wins the majority of a fixed number of rounds", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [MbUnit.Framework.FixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [MbUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [MbUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [MbUnit.Framework.TestAttribute()]
        [MbUnit.Framework.DescriptionAttribute("Two players, three round game")]
        public virtual void TwoPlayersThreeRoundGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two players, three round game", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have chosen a best of 3 game");
#line 8
 testRunner.When("I win 2 rounds");
#line 9
 testRunner.Then("the game should be complete");
#line hidden
            this.ScenarioCleanup();
        }
        
        [MbUnit.Framework.TestAttribute()]
        [MbUnit.Framework.DescriptionAttribute("Two players, five round game")]
        public virtual void TwoPlayersFiveRoundGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two players, five round game", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I have chosen a best of 5 game");
#line 13
 testRunner.When("I win 2 rounds");
#line 14
 testRunner.Then("the game should not be complete");
#line hidden
            this.ScenarioCleanup();
        }
        
        [MbUnit.Framework.TestAttribute()]
        [MbUnit.Framework.DescriptionAttribute("Three players, best of five")]
        public virtual void ThreePlayersBestOfFive()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Three players, best of five", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("a game with 3 players and best of 5");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Round",
                        "Player 1",
                        "Player 2",
                        "Player 3"});
            table1.AddRow(new string[] {
                        "1",
                        "win",
                        "lose",
                        "lose"});
            table1.AddRow(new string[] {
                        "2",
                        "win",
                        "lose",
                        "lose"});
            table1.AddRow(new string[] {
                        "3",
                        "lose",
                        "win",
                        "lose"});
            table1.AddRow(new string[] {
                        "4",
                        "win",
                        "lose",
                        "lose"});
#line 18
 testRunner.When("the following rounds are played", ((string)(null)), table1);
#line 24
 testRunner.Then("player 1 should be the winner");
#line hidden
            this.ScenarioCleanup();
        }
        
        [MbUnit.Framework.TestAttribute()]
        [MbUnit.Framework.DescriptionAttribute("Three players, best of seven")]
        public virtual void ThreePlayersBestOfSeven()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Three players, best of seven", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("a game with 3 players and best of 5");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Round",
                        "Player 1",
                        "Player 2",
                        "Player 3"});
            table2.AddRow(new string[] {
                        "1",
                        "win",
                        "lose",
                        "lose"});
            table2.AddRow(new string[] {
                        "2",
                        "lose",
                        "win",
                        "lose"});
            table2.AddRow(new string[] {
                        "3",
                        "lose",
                        "lose",
                        "win"});
            table2.AddRow(new string[] {
                        "4",
                        "draw",
                        "draw",
                        "draw"});
            table2.AddRow(new string[] {
                        "5",
                        "lose",
                        "win",
                        "lose"});
#line 28
 testRunner.When("the following rounds are played", ((string)(null)), table2);
#line 35
 testRunner.Then("player 2 should be the winner");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
